// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhUsrG8kdhDsc4SQhRloFPXMlHcfLrJnI',
    appId: '1:663098562832:web:3ed1f206adbb40d59a6d95',
    messagingSenderId: '663098562832',
    projectId: 'nab-store',
    authDomain: 'nab-store.firebaseapp.com',
    storageBucket: 'nab-store.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAngOISowwEJrIG750Scry3y_SWJ3LLsg',
    appId: '1:663098562832:android:81d7fbbf472cbd129a6d95',
    messagingSenderId: '663098562832',
    projectId: 'nab-store',
    storageBucket: 'nab-store.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0FQ5YPz4SkonbsZBOptROAq5v391cXg',
    appId: '1:663098562832:ios:3f8519d1c171cd2a9a6d95',
    messagingSenderId: '663098562832',
    projectId: 'nab-store',
    storageBucket: 'nab-store.appspot.com',
    iosClientId: '663098562832-kprog5ki83k51jqmbu4nlf6j1lgkapva.apps.googleusercontent.com',
    iosBundleId: 'com.example.nabStore',
  );
}
